'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace CVS
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ClaimVerifyServiceRequest", [Namespace]:="http://svcs.workforcesafety.com/claims/verify"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ClaimVerifyServiceRequest
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RequestIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserPwField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SSNField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirstNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateOfBirthField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RequestId() As String
            Get
                Return Me.RequestIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RequestIdField, value) <> true) Then
                    Me.RequestIdField = value
                    Me.RaisePropertyChanged("RequestId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserName() As String
            Get
                Return Me.UserNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserNameField, value) <> true) Then
                    Me.UserNameField = value
                    Me.RaisePropertyChanged("UserName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserPw() As String
            Get
                Return Me.UserPwField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserPwField, value) <> true) Then
                    Me.UserPwField = value
                    Me.RaisePropertyChanged("UserPw")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public Property SSN() As String
            Get
                Return Me.SSNField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SSNField, value) <> true) Then
                    Me.SSNField = value
                    Me.RaisePropertyChanged("SSN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstNameField, value) <> true) Then
                    Me.FirstNameField = value
                    Me.RaisePropertyChanged("FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public Property LastName() As String
            Get
                Return Me.LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastNameField, value) <> true) Then
                    Me.LastNameField = value
                    Me.RaisePropertyChanged("LastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public Property DateOfBirth() As Date
            Get
                Return Me.DateOfBirthField
            End Get
            Set
                If (Me.DateOfBirthField.Equals(value) <> true) Then
                    Me.DateOfBirthField = value
                    Me.RaisePropertyChanged("DateOfBirth")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ClaimVerifyServiceResponse", [Namespace]:="http://svcs.workforcesafety.com/claims/verify"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ClaimVerifyServiceResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RequestIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaimListField As CVS.ClaimListType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExceptionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RequestId() As String
            Get
                Return Me.RequestIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RequestIdField, value) <> true) Then
                    Me.RequestIdField = value
                    Me.RaisePropertyChanged("RequestId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public Property ClaimList() As CVS.ClaimListType
            Get
                Return Me.ClaimListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaimListField, value) <> true) Then
                    Me.ClaimListField = value
                    Me.RaisePropertyChanged("ClaimList")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public Property Status() As String
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public Property Exception() As String
            Get
                Return Me.ExceptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExceptionField, value) <> true) Then
                    Me.ExceptionField = value
                    Me.RaisePropertyChanged("Exception")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ClaimListType", [Namespace]:="http://svcs.workforcesafety.com/claims/verify", ItemName:="Claim"),  _
     System.SerializableAttribute()>  _
    Public Class ClaimListType
        Inherits System.Collections.Generic.List(Of CVS.Claim)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Claim", [Namespace]:="http://svcs.workforcesafety.com/claims/verify"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Claim
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClaimStatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DateOfBirthField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmployerNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirstNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InjuryDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MiddleNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PayStatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeOfInjuryField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ClaimStatus() As String
            Get
                Return Me.ClaimStatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ClaimStatusField, value) <> true) Then
                    Me.ClaimStatusField = value
                    Me.RaisePropertyChanged("ClaimStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DateOfBirth() As Date
            Get
                Return Me.DateOfBirthField
            End Get
            Set
                If (Me.DateOfBirthField.Equals(value) <> true) Then
                    Me.DateOfBirthField = value
                    Me.RaisePropertyChanged("DateOfBirth")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmployerName() As String
            Get
                Return Me.EmployerNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmployerNameField, value) <> true) Then
                    Me.EmployerNameField = value
                    Me.RaisePropertyChanged("EmployerName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstNameField, value) <> true) Then
                    Me.FirstNameField = value
                    Me.RaisePropertyChanged("FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property InjuryDate() As Date
            Get
                Return Me.InjuryDateField
            End Get
            Set
                If (Me.InjuryDateField.Equals(value) <> true) Then
                    Me.InjuryDateField = value
                    Me.RaisePropertyChanged("InjuryDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastName() As String
            Get
                Return Me.LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastNameField, value) <> true) Then
                    Me.LastNameField = value
                    Me.RaisePropertyChanged("LastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MiddleName() As String
            Get
                Return Me.MiddleNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MiddleNameField, value) <> true) Then
                    Me.MiddleNameField = value
                    Me.RaisePropertyChanged("MiddleName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PayStatus() As String
            Get
                Return Me.PayStatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PayStatusField, value) <> true) Then
                    Me.PayStatusField = value
                    Me.RaisePropertyChanged("PayStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TypeOfInjury() As String
            Get
                Return Me.TypeOfInjuryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TypeOfInjuryField, value) <> true) Then
                    Me.TypeOfInjuryField = value
                    Me.RaisePropertyChanged("TypeOfInjury")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://svcs.workforcesafety.com/claims/verify", ConfigurationName:="CVS.IClaimVerifyService")>  _
    Public Interface IClaimVerifyService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://svcs.workforcesafety.com/claims/verify/IClaimVerifyService/Verify", ReplyAction:="http://svcs.workforcesafety.com/claims/verify/IClaimVerifyService/VerifyResponse")>  _
        Function Verify(ByVal requestData As CVS.ClaimVerifyServiceRequest) As CVS.ClaimVerifyServiceResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://svcs.workforcesafety.com/claims/verify/IClaimVerifyService/Verify", ReplyAction:="http://svcs.workforcesafety.com/claims/verify/IClaimVerifyService/VerifyResponse")>  _
        Function VerifyAsync(ByVal requestData As CVS.ClaimVerifyServiceRequest) As System.Threading.Tasks.Task(Of CVS.ClaimVerifyServiceResponse)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IClaimVerifyServiceChannel
        Inherits CVS.IClaimVerifyService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ClaimVerifyServiceClient
        Inherits System.ServiceModel.ClientBase(Of CVS.IClaimVerifyService)
        Implements CVS.IClaimVerifyService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Verify(ByVal requestData As CVS.ClaimVerifyServiceRequest) As CVS.ClaimVerifyServiceResponse Implements CVS.IClaimVerifyService.Verify
            Return MyBase.Channel.Verify(requestData)
        End Function
        
        Public Function VerifyAsync(ByVal requestData As CVS.ClaimVerifyServiceRequest) As System.Threading.Tasks.Task(Of CVS.ClaimVerifyServiceResponse) Implements CVS.IClaimVerifyService.VerifyAsync
            Return MyBase.Channel.VerifyAsync(requestData)
        End Function
    End Class
End Namespace
